version: "3.8"
services:
  web:
    container_name: moment-web
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=http://moment-api:${API_PORT}
      dockerfile: apps/web/Dockerfile.mono
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - api
    networks:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://moment-api:${API_PORT}

  api:
    container_name: moment-api
    build:
      context: .
      dockerfile: apps/api/Dockerfile.mono
    ports:
      - "${API_PORT}:4000"
    depends_on:
      - database
    networks:
      - api
      - database
    environment:
      - PORT=4000
      - DATABASE_URL=mongodb://moment-database:27017/moment
      - JWT_SECRET=${API_JWT_SECRET}
      - JWT_EXPIRES_IN=${API_JWT_EXPIRES_IN}

  database:
    container_name: moment-database
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - database

networks:
  api:
    driver: bridge
  database:
    driver: bridge
